service: sls-api-management

frameworkVersion: "2"

#resolves variable usage imported from default-customers.js in provider.apiGateway.apiKeys
variablesResolutionMode: "20210326"

provider:
  name: aws
  runtime: nodejs12.x
  region: 'us-east-1'
  profile: node-serveless
  lambdaHashingVersion: 20201221
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - apigateway:GET
            - apigateway:POST
          Resource:
            - arn:aws:apigateway:${self:provider.region}::/*

  apiGateway:
    apiKeys:
      - free: ${file(./config/customers/default-customers.js):free}
      - paid: ${file(./config/customers/default-customers.js):paid}
    usagePlan:
      - free:
          quota:
            limit: 5
            period: MONTH
          #flow operations control
          throttle:
            burstLimit: 200
            #limit per seconds
            rateLimit: 200
      - paid:
          quota:
            limit: 1000
            period: DAY
          throttle:
            burstLimit: 400
            #limit per seconds
            rateLimit: 50

package:
  excludeDevDependencies: true

plugins:
  - serverless-offline

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: get
          private: true
  getUsage:
    handler: handler.usage
    events:
      - http:
          path: getUsage
          method: get
  getUsagePlans:
    handler: handler.usagePlans
    events:
      - http:
          path: getUsagePlans
          method: get
